rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC
    password: admin
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create