management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: auth-spring-boot
    description: An auth app
    author: David Rodriguez
    version: '@project.version@'
spring:
  profiles:
    active: prod